// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBugTpSlK9eEfq5u3pJ-AfE_t2ZKVmB19g',
    appId: '1:1033453626934:web:98669c9425183f6fe6da97',
    messagingSenderId: '1033453626934',
    projectId: 'chat-app-ab30a',
    authDomain: 'chat-app-ab30a.firebaseapp.com',
    storageBucket: 'chat-app-ab30a.appspot.com',
    measurementId: 'G-QB78Q1Q1B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmjxTPwf-OZzdoDMMcpoFE5nMVQCIv9Qw',
    appId: '1:1033453626934:android:46a54811eb1d4115e6da97',
    messagingSenderId: '1033453626934',
    projectId: 'chat-app-ab30a',
    storageBucket: 'chat-app-ab30a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtvz4AE3xxo9cgYeYghF4JD80b8fkJH2A',
    appId: '1:1033453626934:ios:1b6a2fd2cfa6b7b6e6da97',
    messagingSenderId: '1033453626934',
    projectId: 'chat-app-ab30a',
    storageBucket: 'chat-app-ab30a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtvz4AE3xxo9cgYeYghF4JD80b8fkJH2A',
    appId: '1:1033453626934:ios:1b6a2fd2cfa6b7b6e6da97',
    messagingSenderId: '1033453626934',
    projectId: 'chat-app-ab30a',
    storageBucket: 'chat-app-ab30a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBugTpSlK9eEfq5u3pJ-AfE_t2ZKVmB19g',
    appId: '1:1033453626934:web:dde9d185f9d25ca1e6da97',
    messagingSenderId: '1033453626934',
    projectId: 'chat-app-ab30a',
    authDomain: 'chat-app-ab30a.firebaseapp.com',
    storageBucket: 'chat-app-ab30a.appspot.com',
    measurementId: 'G-7NV7GPM9JE',
  );
}
